### ISSUE TITLE
Power BI Actions with azure devops(BIOPS)

### ISSUE THREAD

**Issue by nikmk05** [jayendranarumugam/PowerBI-CICD#7]
Hi Jay,
I am able to deploy CICD pipeline.
But,
The requirement is to Deploy file from Artifact to DEV workspace and from Dev workspace to PROD workspace.
Currently for both DEV and PROD the file is uploading from artifacts.
Please help to meet the requirement.
I am using Azure repo, Power Bi actions, Power BI service(Admin access).

Thanks
Nikhil.
<img width="493" alt="image" src="https://user-images.githubusercontent.com/121431424/233575805-8a374d91-c62b-407b-8fde-c96b46383d69.png">

**Comment by jayendranarumugam** [comment]
Hi @nikmk05  the fundamental purpose of using an artifact is to `build once deploy anywhere` meaning you should have the same (pbix)artifact and deploy on Dev,QA and PROD. 

Your requirement deviates from the most fundamental DevOps concept. 

Also I'm not sure what exactly you are trying to achieve with your requirement which is why you want to extract the same pbix file that you deployed in Dev (from artifact) to PROD ? Aren't they are same pbix files ?

**Comment by jayendranarumugam** [comment]
Hi @nikmk05 I'm closing this for now. If you need any help further let me know.
